== Makefile

Este es un ejemplo de un Makefile. Básicamente obtiene un listado de todos los ficheros fuente
*.f90* del directorio *src* y genera una lista de targets que asocia al directorio *app*.

[source,makefile]
--
FC = gfortran
CAF = caf
SRC = $(wildcard src/*.f90)
FILES_NO_EXT = $(notdir $(SRC))
TARGETS = $(addprefix app/,$(FILES_NO_EXT:.f90=))

# Modules
MOD_SRC = $(wildcard src/mod/*.f)
MOD_TARGETS = $(addprefix app/mod/,$(notdir $(MOD_SRC:.f=.mod)))

# Arguments
ARGS = -Wall -Wextra -std=f2018 -O3 -pedantic -fdec-math -ffree-form -Imod

all: app mod $(TARGETS)

# Make target directory
app mod:
	@mkdir -p app
	@mkdir -p mod

# Caso genérico
app/%: src/%.f90 
	$(FC) $(ARGS) $< -o $@

clean:
	@rm -f $(TARGETS)
	@rm -f mod/*.mod mod/*.o
--


Este otro lo he usado más y me da buenos resultados

[source,makefile]
--
FC = gfortran
CAF = caf
SRC = $(wildcard src/*.f)
FILES_NO_EXT = $(notdir $(SRC))
TARGETS = $(addprefix app/,$(FILES_NO_EXT:.f=))

# Modules
MOD_SRC = $(wildcard src/mod/*.f)
MOD_TARGETS = $(addprefix app/mod/,$(notdir $(MOD_SRC:.f=.mod)))

# Arguments
#ARGS = -Wall -Wextra -std=f2018 -O3 -pedantic -fdec-math -ffree-form -Imod
ARGS = -std=f2018 -ffree-form -Imod


all: app mod $(TARGETS)

# Make target directory
app mod:
	@mkdir -p app
	@mkdir -p mod

# Caso genérico
app/%: src/%.f 
	$(FC) $(ARGS) $< -o $@

clean:
	@rm -f $(TARGETS)
	@rm -f mod/*.mod mod/*.o
--
